### ISSUE TITLE
想请问，这是啥意思？

### ISSUE THREAD

**Issue by 150135979803** [yzhangcs/SoTu#5]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\SoTu\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "d:\sotu\venv\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "d:\sotu\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "d:\sotu\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\sotu\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\sotu\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\sotu\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\SoTu\venv\vision\bof.py", line 32, in extract
    self.extract()
  File "D:\SoTu\venv\vision\bof.py", line 81, in extract
    prj_all = np.vstack([prj for prj in projections])
  File "d:\sotu\venv\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError

**Comment by yzhangcs** [comment]
内存不够，向量占用空间过多

宇
Soochow University

发件人: 150135979803<mailto:notifications@github.com>
发送时间: 2020年3月24日 19:58
收件人: yzhangcs/SoTu<mailto:SoTu@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [yzhangcs/SoTu] 想请问，这是啥意思？ (#5)


Traceback (most recent call last):
File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "c:\users\administrator\appdata\local\programs\python\python35\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "D:\SoTu\venv\Scripts\flask.exe_main.py", line 7, in
File "d:\sotu\venv\lib\site-packages\flask\cli.py", line 966, in main
cli.main(prog_name="python -m flask" if as_module else None)
File "d:\sotu\venv\lib\site-packages\flask\cli.py", line 586, in main
return super(FlaskGroup, self).main(*args, **kwargs)
File "d:\sotu\venv\lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "d:\sotu\venv\lib\site-packages\click\core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "d:\sotu\venv\lib\site-packages\click\core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "d:\sotu\venv\lib\site-packages\click\core.py", line 610, in invoke
return callback(*args, **kwargs)
File "D:\SoTu\venv\vision\bof.py", line 32, in extract
self.extract()
File "D:\SoTu\venv\vision\bof.py", line 81, in extract
prj_all = np.vstack([prj for prj in projections])
File "d:\sotu\venv\lib\site-packages\numpy\core\shape_base.py", line 234, in vstack
return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError

―

**Comment by 150135979803** [comment]
好了，我删除一部分图片就可以了，效果不错。我电脑是16G内存。谢谢你的解答。
